FROM palfrey/rustup-watchexec:1.26 as watchexec

FROM golang:1.13

WORKDIR $GOPATH/src/github.com/markelog/probos/back

COPY go.mod .
COPY go.sum .

RUN go mod download

COPY --from=watchexec /root/.cargo/bin/watchexec /bin/
COPY . ./
